version: '3.4'
services:

  awstats:
    build: .
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      #php-fpm
      - "9000:9000"

    volumes:
      - /srv/:/srv/
      - /srv/db-awstats/:/var/lib/awstats/


